# Generated by Django 5.1.4 on 2025-09-26 14:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')], verbose_name='phone number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='profile picture')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='account created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='account updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='customReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.CharField(blank=True, max_length=255, null=True, verbose_name='favorite genres')),
                ('subscribed_newsletter', models.BooleanField(default=False, verbose_name='subscribed to newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='profile created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='profile updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reader profile',
                'verbose_name_plural': 'reader profiles',
            },
        ),
    ]
