# Generated by Django 5.1.4 on 2025-09-26 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255, verbose_name='element ID')),
                ('page_url', models.URLField(verbose_name='page URL')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='clicked at')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='session ID')),
                ('referrer_url', models.URLField(blank=True, null=True, verbose_name='referrer URL')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'click event',
                'verbose_name_plural': 'click events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=255, verbose_name='form ID')),
                ('page_url', models.URLField(verbose_name='page URL')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='session ID')),
                ('referrer_url', models.URLField(blank=True, null=True, verbose_name='referrer URL')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('success', models.BooleanField(default=True, verbose_name='submission success')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(verbose_name='page URL')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='viewed at')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='session ID')),
                ('referrer_url', models.URLField(blank=True, null=True, verbose_name='referrer URL')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'page view',
                'verbose_name_plural': 'page views',
                'ordering': ['-timestamp'],
            },
        ),
    ]
